import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, Suspense, lazy } from "react";
import LoadingScreen from "../components/LoadingScreen";
import HeroContent from "../components/HeroContent";
import InputBox from "../components/InputBox";
import Explore from "./explore";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Timestone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <HeroContent />
          <InputBox />
          <Explore />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
