import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, Suspense, lazy } from "react";
import LoadingScreen from "../components/LoadingScreen";
import HeroContent from "../components/HeroContent";
import InputBox from "../components/InputBox";
import Explore from "./explore";
import MainLayout from "../layouts/MainLayout";

function Landing() {
  return (
    <>
      <Head>
        <title>Timestone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <HeroContent />
        <InputBox />
        <Explore />
      </>

      <footer></footer>
    </>
  );
};

Landing.getLayout = (page: any) => <MainLayout>{page}</MainLayout>;

export default Landing;
